window.LANNA_PIZZA_FLAVORS = [
  ['4 QUEIJOS', 'Molho de tomate, mussarela, parmesão, provolone, catupiry e orégano.', '', 'salgada'],
  ['5 QUEIJOS', 'Molho de tomate, mussarela, parmesão, provolone, catupiry, cheddar e orégano.', '', 'salgada'],
  ['6 QUEIJOS', 'Molho de tomate, mussarela, parmesão, provolone, catupiry, gorgonzola, cheddar e orégano.', '', 'salgada'],
  ['À MODA DA CASA', 'Molho de tomate, mussarela, strogonoff de frango, pimentão, bacon, palmito e orégano.', '', 'salgada'],
  ['À MODA DO CHEFE', 'Molho de tomate, mussarela, strogonoff de carne, bacon, palmito, pimentão e orégano.', '', 'salgada'],
  ['AMERICANA', 'Molho de tomate, mussarela, calabresa, bacon, ovo, cebola e orégano.', '', 'salgada'],
  ['ATUM', 'Molho de tomate, mussarela, atum e orégano.', 'R$ 5,00', 'salgada'],
  ['ATUM COM CEBOLA', 'Molho de tomate, mussarela, atum, cebola e orégano.', 'R$ 5,00', 'salgada'],
  ['ALHO E ÓLEO', 'Molho de tomate, mussarela, alho, azeite e orégano.', '', 'salgada'],
  ['BAIANA', 'Molho de tomate, mussarela, calabresa, cebola, tomate, molho de pimenta e orégano.', '', 'salgada'],
  ['BACON COM CHEDDAR', 'Molho de tomate, mussarela, bacon, cheddar e orégano.', '', 'salgada'],
  ['BACON', 'Molho de tomate, mussarela, bacon e orégano.', '', 'salgada'],
  ['BACON COM MILHO E CHEDDAR', 'Molho de tomate, mussarela, bacon, cheddar, milho e orégano.', '', 'salgada'],
  ['BACON COM MILHO', 'Molho de tomate, mussarela, bacon, milho e orégano.', '', 'salgada'],
  ['BRÓCOLIS', 'Molho de tomate, mussarela, brócolis e orégano.', '', 'salgada'],
  ['BRÓCOLIS COM BACON', 'Molho de tomate, mussarela, brócolis, bacon e orégano.', '', 'salgada'],
  ['BRÓCOLIS COM BACON E CHEDDAR', 'Molho de tomate, mussarela, brócolis, bacon, cheddar e orégano.', 'R$ 5,00', 'salgada'],
  ['BRÓCOLIS COM CHEDDAR', 'Molho de tomate, mussarela, brócolis, bacon e orégano.', '', 'salgada'],
  ['CALABRESA COM BACON', 'Molho de tomate, mussarela, calabresa, bacon e orégano.', '', 'salgada'],
  ['CALABRESA COM MILHO', 'Molho de tomate, mussarela, calabresa, milho e orégano.', '', 'salgada'],
  ['CALABRESA', 'Molho de tomate, mussarela, calabresa e orégano.', '', 'salgada'],
  ['CALABRESA COM ALHO', 'Molho de tomate, mussarela, calabresa, alho e orégano.', '', 'salgada'],
  ['CALABRESA COM CEBOLA', 'Molho de tomate, mussarela, calabresa, cebola e orégano.', '', 'salgada'],
  ['CATUPIRY', 'Molho de tomate, mussarela, catupiry e orégano.', '', 'salgada'],
  ['CHEDDAR', 'Molho de tomate, mussarela, cheddar e orégano.', '', 'salgada'],
  ['CANADENSE', 'Molho de tomate, mussarela, lombo, palmito, milho e orégano.', '', 'salgada'],
  ['CROCANTE', 'Molho de tomate, mussarela, frango, bacon, milho, batata palha e orégano.', '', 'salgada'],
  ['DA HORA', 'Molho de tomate, mussarela, frango, bacon, milho, tomate e orégano.', '', 'salgada'],
  ['ELA E ELE', 'Molho de tomate, mussarela, presunto, tomate e orégano.', '', 'salgada'],
  ['ESCAROLA COM BACON', 'Molho de tomate, mussarela, escarola, bacon e orégano.', '', 'salgada'],
  ['ESCAROLA COM ALHO', 'Molho de tomate, mussarela, escarola, alho e orégano.', '', 'salgada'],
  ['ESPECIAL', 'Molho de tomate, mussarela, milho, palmito, bacon, calabresa e orégano.', '', 'salgada'],
  ['FRANGO COM CHEDDAR', 'Molho de tomate, mussarela, frango, cheddar e orégano.', '', 'salgada'],
  ['FRANGO ESPECIAL', 'Molho de tomate, mussarela, frango, catupiry, milho e orégano.', '', 'salgada'],
  ['FILÉ AO ALHO', 'Molho de tomate, mussarela, carne de gado, alho e orégano.', '', 'salgada'],
  ['FRANCESA', 'Molho de tomate, mussarela, catupiry, palmito, azeitonas e orégano.', '', 'salgada'],
  ['FILÉ NA MOSTARDA', 'Molho de tomate, mussarela, carne de gado, mostarda e orégano.', '', 'salgada'],
  ['FRANGO', 'Molho de tomate, mussarela, frango e orégano.', '', 'salgada'],
  ['FRANGO COM ALHO', 'Molho de tomate, mussarela, frango, alho e orégano.', '', 'salgada'],
  ['FRANGO COM BACON', 'Molho de tomate, mussarela, frango, bacon e orégano.', '', 'salgada'],
  ['FRANGO COM CATUPIRY', 'Molho de tomate, mussarela, frango, catupiry e orégano.', '', 'salgada'],
  ['GAÚCHA', 'Molho de tomate, mussarela, salame italiano, cebola puxada no shoyu e orégano.', 'R$ 5,00', 'salgada'],
  ['LA TRUTA', 'Molho de tomate, mussarela, lombo, catupiry, champignon e orégano.', '', 'salgada'],
  ['LOMBINHO', 'Molho de tomate, mussarela, lombo canadense e orégano.', '', 'salgada'],
  ['LOMBINHO COM CATUPIRY', 'Molho de tomate, mussarela, lombinho, catupiry e orégano.', '', 'salgada'],
  ['LOMBINHO COM CHEDDAR', 'Molho de tomate, mussarela, lombinho, cheddar e orégano.', '', 'salgada'],
  ['MARGUERITA', 'Molho de tomate, mussarela, rodelas de tomate e manjericão.', '', 'salgada'],
  ['MILHO VERDE', 'Molho de tomate, mussarela, milho verde e orégano.', '', 'salgada'],
  ['MILIONÁRIA', 'Molho de tomate, mussarela, milho, catupiry e orégano.', '', 'salgada'],
  ['MINEIRA', 'Molho de tomate, mussarela, milho, ervilha, palmito, catupiry e orégano.', '', 'salgada'],
  ['MUSSARELA', 'Molho de tomate, mussarela e orégano.', '', 'salgada'],
  ['NAPOLITANA', 'Molho de tomate, mussarela, rodelas de tomate, parmesão e orégano.', '', 'salgada'],
  ['PALMITO', 'Molho de tomate, mussarela, palmito e orégano.', '', 'salgada'],
  ['PAULISTA', 'Molho de tomate, mussarela, ervilha, palmito, azeitona, rodelas de tomate e orégano.', '', 'salgada'],
  ['PORTUGUESA', 'Molho de tomate, mussarela, presunto, anéis de cebola, azeitona, ovo e orégano.', '', 'salgada'],
  ['PRIMAVERA', 'Molho de tomate, mussarela, atum, catupiry, milho verde e orégano.', 'R$ 5,00', 'salgada'],
  ['PROVOLONE', 'Molho de tomate, mussarela, provolone e orégano.', '', 'salgada'],
  ['SALAMINHO ITALIANO', 'Molho de tomate, mussarela, salaminho e orégano.', 'R$ 5,00', 'salgada'],
  ['SALAMINHO ACEBOLADO', 'Molho de tomate, mussarela, salaminho, cebola e orégano.', 'R$ 5,00', 'salgada'],
  ['SICILIANA', 'Molho de tomate, mussarela, bacon, champignon, cebola e orégano.', 'R$ 5,00', 'salgada'],
  ['STROGONOFF DE CARNE', 'Molho de tomate, mussarela, strogonoff de carne, orégano e batata palha.', '', 'salgada'],
  ['STROGONOFF DE FRANGO', 'Molho de tomate, mussarela, strogonoff de frango, orégano e batata palha.', '', 'salgada'],
  ['TOMATE SECO COM RÚCULA', 'Molho de tomate, mussarela, tomate seco e rúcula.', '', 'salgada'],
  ['TOMATE SECO COM PALMITO', 'Molho de tomate, mussarela, tomate seco, palmito e orégano.', '', 'salgada'],
  ['TROPICAL', 'Molho de tomate, mussarela, lombo, abacaxi e orégano.', 'R$ 5,00', 'salgada'],
  ['VEGETARIANA', 'Molho de tomate, mussarela, tomate, palmito, milho, ervilha e orégano.', '', 'salgada'],
  ['ALCATRA COM CREAM CHEESE', 'Molho de tomate, mussarela, alcatra, cream cheese e orégano.', 'R$ 12,00', 'salgada'],
  ['ALCATRA COM BARBECUE', 'Molho de tomate, mussarela, alcatra, barbecue e orégano.', 'R$ 12,00', 'salgada'],
  ['ALCATRA COM CREME DE ALHO', 'Molho de tomate, mussarela, alcatra, creme de alho especial e orégano.', 'R$ 12,00', 'salgada'],
  ['CANI-KAMA COM CREAM CHEESE', 'Molho de tomate, mussarela, cani-kama, cream cheese e orégano.', 'R$ 8,00', 'salgada'],
  ['MEXICANA COM NACHOS', 'Molho de tomate, mussarela, alcatra, cheddar, Doritos e orégano.', 'R$ 12,00', 'salgada'],
  ['PEPERONE', 'Molho de tomate, mussarela, peperone e orégano.', 'R$ 8,00', 'salgada'],
  ['PRIME FIT', 'Molho de tomate, mussarela, peito de peru, cream cheese, tomate-cereja e manjericão.', 'R$ 10,00', 'salgada'],
  ['SALMÃO COM CREAM CHEESE', 'Molho de tomate, mussarela, salmão, cream cheese e orégano.', 'R$ 12,00', 'salgada'],
  ['BANANA', 'Leite condensado, mussarela, banana, canela e açúcar mascavo.', '', 'doce'],
  ['BANANA NEVADA', 'Leite condensado, mussarela, banana, chocolate branco, canela e açúcar mascavo.', '', 'doce'],
  ['BRIGADEIRO', 'Leite condensado, mussarela, chocolate preto e granulado.', '', 'doce'],
  ['CALIFÓRNIA', 'Leite condensado, mussarela, pêssego, abacaxi, figo e cereja.', '', 'doce'],
  ['COCO', 'Leite condensado, mussarela e flocos de coco.', '', 'doce'],
  ['CONFETE PRETO', 'Leite condensado, mussarela, chocolate preto e confeite colorido.', '', 'doce'],
  ['CHOCOLATE BRANCO', 'Leite condensado, mussarela e chocolate branco.', '', 'doce'],
  ['CHOCOLATE PRETO', 'Leite condensado, mussarela e chocolate preto.', '', 'doce'],
  ['CHOKITO PRETO', 'Leite condensado, mussarela, chocolate preto e flocos.', '', 'doce'],
  ['CHOCONANA', 'Leite condensado, mussarela, banana, chocolate preto, canela e açúcar mascavo.', '', 'doce'],
  ['DOIS AMORES', 'Leite condensado, mussarela, chocolate branco, chocolate preto e morango.', '', 'doce'],
  ['DOIS CORAÇÕES', 'Leite condensado, mussarela, chocolate branco e chocolate preto.', '', 'doce'],
  ['FLORESTA NEGRA', 'Leite condensado, mussarela, chocolate preto e cereja.', 'R$ 5,00', 'doce'],
  ['OURO BRANCO', 'Leite condensado, mussarela, chocolate branco e bombom.', '', 'doce'],
  ['PRESTÍGIO', 'Leite condensado, mussarela, chocolate preto e flocos de coco.', '', 'doce'],
  ['SONHO DE VALSA', 'Leite condensado, mussarela, chocolate preto e bombom.', '', 'doce'],
  ['SEDUÇÃO', 'Leite condensado, mussarela, morango e chocolate branco.', '', 'doce'],
  ['SENSAÇÃO', 'Leite condensado, mussarela, morango e chocolate preto.', '', 'doce'],
  ['DELÍCIA DE MORANGO', 'Leite condensado, mussarela, chocolate branco, morango e suspiro.', 'R$ 8,00', 'doce'],
  ['FONDUE', 'Leite condensado, mussarela, chocolate preto, morango, kiwi e uva.', 'R$ 12,00', 'doce'],
  ['NUTELLA COM LEITE NINHO', 'Leite condensado, mussarela, creme de avelã, leite Ninho e morango.', 'R$ 12,00', 'doce'],
  ['OVO MALTINE', 'Leite condensado, mussarela, chocolate preto e ovo maltine.', 'R$ 8,00', 'doce']
];
